export const ACTION_SIGN_UP = "ACTION_SIGN_UP";
export const ACTION_SIGN_IN = "ACTION_SIGN_IN";
export const ACTION_SIGN_OUT = "ACTION_SIGN_OUT";
export const ACTION_DIALOG_OPEN = "ACTION_DIALOG_OPEN";
export const ACTION_DIALOG_CLOSE = "ACTION_DIALOG_CLOSE";
export const ACTION_PROGRESS_START = "ACTION_PROGRESS_START";
export const ACTION_PROGRESS_STOP = "ACTION_PROGRESS_STOP";
export const ACTION_SIGN_IN_AS_SELLER = "ACTION_SIGN_IN_AS_SELLER";
export const ACTION_SIGN_UP_AS_SELLER = "ACTION_SIGN_UP_AS_SELLER";
export const ACTION_SIGN_OUT_SELLER = "ACTION_SIGN_OUT_SELLER";
export const IS_ALREADY_A_SELLER = "IS_ALREADY_A_SELLER";
export const HOMEPAGE_GET_GIGS = "HOMEPAGE_GET_GIGS";
export const ACTION_APPEND_POST_A_GIG_DATA = "APPEND_POST_A_GIG_DATA";
export const ACTION_SET_STEPS_POST_A_GIG = "ACTION_SET_STEPS_POST_A_GIG";
export const ACTION_APPEND_MERCHANT_REGISTER =
  "ACTION_APPEND_MERCHANT_REGISTER";
export const ACTION_APPEND_GIG_REVIEW = "ACTION_APPEND_GIG_REVIEW";
export const ACTION_CHECKOUT_AFTER_REVIEW = "ACTION_CHECKOUT_AFTER_REVIEW";
export const ACTION_APPEND_CREATE_SELLER_PROFILE =
  "ACTION_APPEND_CREATE_SELLER_PROFILE";
export const ACTION_SET_STEPS_CREATE_SELLER_PROFILE =
  "ACTION_SET_STEPS_CREATE_SELLER_PROFILE";
export const ACTION_OPEN_CHAT_DIALOG = "ACTION_OPEN_CHAT_DIALOG";
export const ACTION_CLOSE_CHAT_DIALOG = "ACTION_CLOSE_CHAT_DIALOG";
export const ACTION_RATING_SHOW = "ACTION_RATING_SHOW"
export const ACTION_RATING_HIDE = "ACTION_RATING_HIDE"
export const ACTION_START_GIG_SEARCH = "ACTION_START_GIG_SEARCH"
export const ACTION_CLEAR_GIG_SEARCH = "ACTION_CLEAR_GIG_SEARCH"
