export const API_ROOT = window.location.hostname == 'onor.world' ? "https://onor.world/api" : "http://18.217.104.109/api"
// development server api
// export const API_ROOT = "http://18.217.104.109/api"
// export const API_ROOT = "http://3.128.180.240/api"
// export const API_ROOT = "http://192.168.1.12:8084/api"
export const WEB_ENDPOINT = "https://onor.world"
export const API_USER_REGISTER = API_ROOT + "/user/register"
export const API_USER_SIGNIN = API_ROOT + "/user/login"
export const API_FETCH_GIGS = API_ROOT + '/product/getAllGigs'
export const API_SELLER_REGISTER = API_ROOT + "/merchant/register"
export const API_SELLER_LOGIN = API_ROOT + "/merchant/login"
export const API_BUYER_POST_A_REQUEST = API_ROOT + "/product/request/postARequest"
export const API_BUYER_POST_A_GIG = API_ROOT + "/product/postAGig"
export const API_FETCH_SINGLE_GIG = API_ROOT + '/product/'
export const API_GIG_SEARCH = API_ROOT + '/product/search'
export const API_FETCH_TASKS_ALL = API_ROOT + '/product/request/getAllProductRequest'
export const API_FETCH_TASKS = API_ROOT + '/product/request/'
export const API_FETCH_ALL_CATEGORIES = API_ROOT + '/category/showAllCategories'
export const API_SAVE_ONOR_PACKAGE = API_ROOT + '/package/addPackage'
export const API_MAKE_ORDER = API_ROOT + '/order/placeOrder'
export const API_MAKE_PAYMENT = API_ROOT + '/order/create-session'
export const API_FETCH_ORDERS = API_ROOT + '/order/user/orderHistory/'
export const API_CANCEL_ORDER = API_ROOT + '/order/cancel/'
export const API_FETCH_MERCHANT_ORDERS = API_ROOT + '/order/merchant/orderHistory/'
export const API_APPROVE_ORDER = API_ROOT + '/order/accept/'
export const MERCHANT_GIGS_LIST = API_ROOT + '/product/merchant/'
export const MERCHANT_GIG_EDIT = API_ROOT + '/product/edit/'
export const FETCH_SINGLE_ORDER_DETAILS = API_ROOT + '/order/'
export const USER_CHANGE_PASSWORD = API_ROOT + '/user/changePassword'
export const API_COMPLETE_ORDER = API_ROOT + '/order/completed/'
export const API_POST_RATINGS = API_ROOT + '/order/ratings/'
export const GET_SELLER_EDIT_PROFILE_DATA = API_ROOT + '/merchant/getById/'
export const GET_BUYER_EDIT_PROFILE_DATA = API_ROOT + '/user/getById/'
export const UPDATE_SELLER_EDIT_PROFILE_DATA = API_ROOT + '/merchant/update/'
export const UPDATE_BUYER_EDIT_PROFILE_DATA = API_ROOT + '/user/update/'
export const API_FETCH_SINGLE_REQUEST = API_ROOT + '/product/request/'
export const API_USER_AVATAR_CHANGE = API_ROOT + '/user/avatar/'
export const API_MERCHANT_AVATAR_CHANGE = API_ROOT + '/merchant/avatar/'
export const READ_CHAT_HEAD_FROM_DB = API_ROOT + "/chat/read"
export const ADD_CHAT_HEAD_TO_DB = API_ROOT + "/chat/add"
export const API_DELIVER_ORDER = API_ROOT + '/order/delivered/'
export const GET_USER_BY_MERCHANT_EMAIL = API_ROOT + '/user/getByEmail'
export const SEND_OTP_FOR_RECOVER_PASSWORD = API_ROOT + '/otpService/sendOtp'
export const VERIFY_OTP = API_ROOT + '/otpService/verifyOtp'
export const EDIT_PACKAGE = API_ROOT + '/package/edit/'